const BODYPART_TYPE =  Object.freeze({
    CELL: Symbol("CELL"),
    SPIKE: Symbol("SPIKE"),
    SHIELD: Symbol("SHIELD"),
    BOUNCE: Symbol("BOUNCE"),
});
module.exports.BODYPART_TYPE = BODYPART_TYPE;
let BODYPART_COST_MUTABLE = {};
BODYPART_COST_MUTABLE[BODYPART_TYPE.CELL] = 15;
BODYPART_COST_MUTABLE[BODYPART_TYPE.SPIKE] = 10;
BODYPART_COST_MUTABLE[BODYPART_TYPE.SHIELD] = 5;
BODYPART_COST_MUTABLE[BODYPART_TYPE.BOUNCE] = 10;
const BODYPART_COST = Object.freeze(BODYPART_COST_MUTABLE);
module.exports.BODYPART_COST = BODYPART_COST;


const MAX_HEALTH = 100;
module.exports.MAX_HEALTH = MAX_HEALTH;

const MAX_INFLATE = 100;
module.exports.MAX_INFLATE = MAX_INFLATE;

const INFLATE_RATE = 2;
module.exports.INFLATE_RATE = INFLATE_RATE;

const REGEN_RATE = 1;
module.exports.REGEN_RATE = REGEN_RATE;

const SPIKE_DMG = 3;
module.exports.SPIKE_DMG = SPIKE_DMG;

const ACTION = Object.freeze({
    MOVE: Symbol("MOVE"),
    DESTROY: Symbol("DESTROY"),
    COLLIDE: Symbol("COLLIDE"),
});
module.exports.ACTION = ACTION;

const CHEATS_ENABLED = true;
module.exports.CHEATS_ENABLED = CHEATS_ENABLED;

const RESOURCE_SIZE_STEP = 10;
module.exports.RESOURCE_SIZE_STEP = RESOURCE_SIZE_STEP;
const RESOURCE_SIZE_MIN = 5;
module.exports.RESOURCE_SIZE_MIN = RESOURCE_SIZE_MIN;
const RESOURCE_SIZE_MAX = 28;
module.exports.RESOURCE_SIZE_MAX = RESOURCE_SIZE_MAX;

const MINING_RATE = 1;
module.exports.MINING_RATE = MINING_RATE;